# The name of this app. Must be unique within a project.
name: "lnclassapp"

type: "ruby:3.0"

dependencies:
    nodejs:
        yarn: "*"

relationships:
    database: 'db:postgresql'

disk: 1024


mounts:
  'web/uploads':
    source: local
    source_path: uploads

hooks:
    build: |
        gem install bundler:2.3.16
        bundle install
    deploy: |
        RACK_ENV=production bundle exec rake db:migrate

web:
    upstream:
        socket_family: unix
    commands:
        start: "unicorn -l $SOCKET -E production config.ru"
    locations:
        "/":
            root: "public"
            passthru: true
            expires: 1h
            allow: true